{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: {{ include "prometheus.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus.fullname" . }}
{{- end }}