apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}